//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIP_LCMP.DataEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AgeDataInput
    {
        public int id { get; set; }
        public Nullable<int> fleetmodelid { get; set; }
        public Nullable<int> colorid { get; set; }
        public Nullable<int> rangestart { get; set; }
        public Nullable<int> rangeend { get; set; }
        public Nullable<int> fleetid { get; set; }
    
        public virtual Fleet Fleet { get; set; }
        public virtual FleetAgeColours FleetAgeColours { get; set; }
        public virtual FleetModel FleetModel { get; set; }
    }
}
