//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIP_LCMP.DataEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class FleetTransactions
    {
        public int id { get; set; }
        public Nullable<int> fleetid { get; set; }
        public Nullable<int> fleetmodelid { get; set; }
        public Nullable<int> equipmentid { get; set; }
        public Nullable<int> costcenterid { get; set; }
        public string prontoplantnumber { get; set; }
        public string pmtasknumber { get; set; }
        public Nullable<int> nextdue { get; set; }
        public string activity { get; set; }
        public Nullable<int> currenthour { get; set; }
        public Nullable<int> oem { get; set; }
        public Nullable<int> frequency { get; set; }
        public Nullable<int> labourduration { get; set; }
        public Nullable<int> labourcost { get; set; }
        public Nullable<int> materialcost { get; set; }
        public Nullable<int> oilcapacity { get; set; }
        public Nullable<int> oilcost { get; set; }
        public Nullable<int> tyrescost { get; set; }
        public Nullable<int> totalcost { get; set; }
        public Nullable<int> lastchange { get; set; }
        public Nullable<int> downtime { get; set; }
    
        public virtual CostCenters CostCenters { get; set; }
        public virtual Equipment Equipment { get; set; }
        public virtual Fleet Fleet { get; set; }
        public virtual FleetModel FleetModel { get; set; }
    }
}
