//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIP_LCMP.DataEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class FleetTransactions
    {
        public int Id { get; set; }
        public Nullable<int> FleetId { get; set; }
        public Nullable<int> FleetModelId { get; set; }
        public Nullable<int> EquipmentId { get; set; }
        public Nullable<int> CostCenterId { get; set; }
        public string ProntoPlantNumber { get; set; }
        public string PMTaskNumber { get; set; }
        public Nullable<int> NextDue { get; set; }
        public string Activity { get; set; }
        public Nullable<int> CurrentHour { get; set; }
        public Nullable<int> OEM { get; set; }
        public Nullable<int> Frequency { get; set; }
        public Nullable<int> LabourDuration { get; set; }
        public Nullable<int> LabourCost { get; set; }
        public Nullable<int> MaterialCost { get; set; }
        public Nullable<int> OilCapacity { get; set; }
        public Nullable<int> OilCost { get; set; }
        public Nullable<int> TyreCost { get; set; }
        public Nullable<int> TotalCost { get; set; }
        public Nullable<int> LastChange { get; set; }
        public Nullable<int> Downtime { get; set; }
    
        public virtual CostCenters CostCenters { get; set; }
        public virtual Equipment Equipment { get; set; }
        public virtual Fleet Fleet { get; set; }
        public virtual FleetModel FleetModel { get; set; }
    }
}
