//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIP_LCMP.DataEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class FleetCostCenterMapping
    {
        public int Id { get; set; }
        public int FleetId { get; set; }
        public int CostCenterId { get; set; }
        public int Count { get; set; }
    
        public virtual CostCenters CostCenters { get; set; }
        public virtual Fleet Fleet { get; set; }
    }
}
