//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIP_LCMP.DataEntities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LCMPEntities : DbContext
    {
        public LCMPEntities()
            : base("name=LCMPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AgeDataInput> AgeDataInput { get; set; }
        public virtual DbSet<CostCenters> CostCenters { get; set; }
        public virtual DbSet<Equipment> Equipment { get; set; }
        public virtual DbSet<Fleet> Fleet { get; set; }
        public virtual DbSet<FleetAgeColours> FleetAgeColours { get; set; }
        public virtual DbSet<FleetCostCenterMapping> FleetCostCenterMapping { get; set; }
        public virtual DbSet<FleetModel> FleetModel { get; set; }
        public virtual DbSet<FleetTransactions> FleetTransactions { get; set; }
        public virtual DbSet<LubricantCost> LubricantCost { get; set; }
        public virtual DbSet<TyreCost> TyreCost { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
