//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIP_LCMP.DataEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TyreCost
    {
        public int id { get; set; }
        public Nullable<int> modelid { get; set; }
        public string specification { get; set; }
        public Nullable<int> price { get; set; }
        public Nullable<int> count { get; set; }
        public Nullable<int> life { get; set; }
    }
}
