//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIP_LCMP.DataEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TyreCost
    {
        public int id { get; set; }
        public int ModelId { get; set; }
        public string Specification { get; set; }
        public int Price { get; set; }
        public int Count { get; set; }
        public int Life { get; set; }
    }
}
